### Import all the packages

In [1]:
import pandas as pd
import nltk
import numpy as np
from numpy import random as npr
import time
import string
import sklearn
import random
# from itertools import chain, imap

In [2]:
# download stopwords and punctuations 
nltk.download('punkt') 
nltk.download("stopwords")

[nltk_data] Downloading package punkt to /Users/dhmjoe/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/dhmjoe/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [3]:

from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
import re
from sklearn import svm
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.model_selection import GridSearchCV
#from operator import itemgetter

### Data Processing

In [6]:
#Read in data
df1 = pd.read_json('/Users/dhmjoe/Desktop/carpe data Haoming/final_50k_221118.json',lines=True)

In [8]:
#Select first 50000 rows
first10 = df1[0:450000]

#Extract business name and content from the first 50000 rows
df2 = first10[["business_name","content"]]

# Create a seperate data frame for labels
label = ["is_entertainment","is_traffic"]

#Extract labels from the first 50000 rows
labeldf = first10[["is_entertainment","is_traffic"]]

labeldf_1 = labeldf["is_entertainment"]
labeldf_2 = labeldf["is_traffic"]
# np.unique(labeldf_2)
np.unique(labeldf_1)
#print(df2)

array([False,  True])

In [9]:
token = []
name = ["business_name","content"]
dic1 = {}
WORD = re.compile(r'\w+')

In [10]:
WORD

re.compile(r'\w+', re.UNICODE)

### Tokenize Data

In [11]:
def regTokenize(text):
    words = WORD.findall(text)
    return words

In [13]:
for i in [0,1]:
    arrx = []
    for j in range(0,450000):
    #for j in range(0,len(df2[name[i]])):
        listx = regTokenize(df2[name[i]][j])
        arrx.append(listx)
    dic1[name[i]] = arrx
# print(dic1)
# dic1 contains all the tokens of business name and contents

### Stop words

In [14]:
stop_words = set(stopwords.words("english"))
for i in range(len(string.punctuation)):    
    stop_words.add(string.punctuation[i])
stop_words.add("'s")
stop_words.add(".....")
print(stop_words)

{'|', 'yourself', 'she', 'wasn', '"', 'off', "couldn't", 'until', "you're", '#', "hasn't", 'myself', 'up', 'weren', 'a', 'should', '&', 'they', 'your', 'both', 'yourselves', 'do', "mightn't", 'with', 'o', "you'd", "hadn't", 'yours', '.', 'any', 'an', 'can', 'don', 'most', 'once', 'wouldn', 'will', 'we', '(', 'ours', "it's", 'them', 'these', 'between', 'during', 'ma', ')', "you've", 't', 'those', 'their', 'i', 'through', 'couldn', 'does', 'then', '{', 'against', 'in', 'down', 'few', 'each', 'under', 'himself', 'mustn', "that'll", '<', '~', 'hers', ';', 'to', 'all', 'aren', 'now', 'more', 'our', '`', 'very', '$', '*', 'same', 'him', 'didn', 'on', '!', 'no', 'herself', 'if', 'just', 'or', 'after', '-', '_', 'because', 'had', 'having', 'm', 'my', "'s", 'what', 'over', "aren't", 've', 'haven', 'whom', '[', 'such', 'nor', 'hasn', 'shan', 'so', 'did', 'the', "you'll", "didn't", 'from', "wasn't", 'ourselves', 'at', 'll', "won't", 'as', 'own', 'this', 'out', 'which', 'again', 'is', "haven't", '

### Word Stemmer

In [15]:
stemmer = PorterStemmer()
# print(dic1)
for i in [0,1]:
    arrc = []
    for j in range(0,len(dic1[name[i]])):
        flist = []
        for z in dic1[name[i]][j]:
            if z.casefold() not in stop_words:
                flist.append(stemmer.stem(z))
        arrc.append(' '.join(flist))
    dic1[name[i]] = arrc
    #print(len(dic1[name[i]]))
    
# print(dic1)

In [16]:
tflist = []
for i in [0,1]:
    tr_idf_model  = TfidfVectorizer(min_df=0.001)
    corpus = dic1[name[i]]
    tf_idf_vector = tr_idf_model.fit_transform(corpus)
    tf_idf_array = tf_idf_vector.toarray()
    words_set = tr_idf_model.get_feature_names_out()
    #print(words_set)
    df_tf_idf= pd.DataFrame(tf_idf_array, columns = words_set)
    tflist.append(df_tf_idf)
    #This is the tf-idf result that we can use for SVM or Simple Bayes
    print(df_tf_idf)
    # print(labeldf[label[i]])
    
    
    '''
    #tfidf = []
    tfidf = [(j,sum(df_tf_idf[j])) for j in words_set]
    tfidf.sort(key=lambda x: x[1],reverse=True)
    print(name[i],tfidf)
    end = time.time()
    print(name[i],end-now)
    now = end'''

         76  ace  aid  american  ampm  angel  antiqu  applianc  arco  art  \
0       0.0  0.0  0.0       0.0   0.0    0.0     0.0       0.0   0.0  0.0   
1       0.0  0.0  0.0       0.0   0.0    0.0     0.0       0.0   0.0  0.0   
2       0.0  0.0  0.0       0.0   0.0    0.0     0.0       0.0   0.0  0.0   
3       0.0  0.0  0.0       0.0   0.0    0.0     0.0       0.0   0.0  0.0   
4       0.0  0.0  0.0       0.0   0.0    0.0     0.0       0.0   0.0  0.0   
...     ...  ...  ...       ...   ...    ...     ...       ...   ...  ...   
449995  0.0  0.0  0.0       0.0   0.0    0.0     0.0       0.0   0.0  0.0   
449996  0.0  0.0  0.0       0.0   0.0    0.0     0.0       0.0   0.0  0.0   
449997  0.0  0.0  0.0       0.0   0.0    0.0     0.0       0.0   0.0  0.0   
449998  0.0  0.0  0.0       0.0   0.0    0.0     0.0       0.0   0.0  0.0   
449999  0.0  0.0  0.0       0.0   0.0    0.0     0.0       0.0   0.0  0.0   

        ...  west  wholesal  wild  wine  wineri  wing  world  yelp  yogurt 

In [17]:
npr.seed(123)
for i in [0,1]:
    for j in [0,1]:
        print(name[i],label[j])
        X_train, X_test, y_train, y_test = train_test_split(tflist[i], labeldf[label[j]], test_size=0.2, random_state=434)
        # create and fit the Naive Bayes model
        nb_model = MultinomialNB()
        #nb_model = GaussianNB()
        nb_model.fit(X_train, y_train)

        # make predictions on the test data
        y_pred = nb_model.predict(X_test)
        
        '''
        param_grid_nb = {
        'var_smoothing': np.logspace(0,-9, num=100)
        }
        nbModel_grid = GridSearchCV(estimator=GaussianNB(), param_grid=param_grid_nb, verbose=1, cv=10, n_jobs=-1)
        nbModel_grid.fit(X_train, y_train)
        print(nbModel_grid.best_estimator_)
        y_pred = nbModel_grid.predict(X_test)
        '''

        # calculate accuracy
        #accuracy = (y_pred == y_test).sum() / len(y_test)
        accuracy = accuracy_score(y_test, y_pred)
        print(f'Accuracy: {accuracy:.2f}')

        print(confusion_matrix(y_test, y_pred), ": is the confusion matrix")

        print(precision_score(y_test, y_pred), ": is the precision score")

        print(recall_score(y_test, y_pred), ": is the recall score")

        print(f1_score(y_test, y_pred), ": is the f1 score")

business_name is_entertainment
Accuracy: 0.92
[[76966   615]
 [ 6461  5958]] : is the confusion matrix
0.9064354176175262 : is the precision score
0.4797487720428376 : is the recall score
0.6274220724515585 : is the f1 score
business_name is_traffic
Accuracy: 0.87
[[ 2347 10119]
 [ 1425 76109]] : is the confusion matrix
0.8826483276893816 : is the precision score
0.9816209662857585 : is the recall score
0.92950745594216 : is the f1 score
content is_entertainment
Accuracy: 0.89
[[77378   203]
 [ 9976  2443]] : is the confusion matrix
0.9232804232804233 : is the precision score
0.1967147113294146 : is the recall score
0.32432791237968805 : is the f1 score
content is_traffic
Accuracy: 0.86
[[  333 12133]
 [  342 77192]] : is the confusion matrix
0.864170165127344 : is the precision score
0.9955890319085821 : is the recall score
0.9252362773359543 : is the f1 score


In [33]:
from sklearn.preprocessing import LabelEncoder 
from sklearn import model_selection, svm
from sklearn.metrics import accuracy_score
# perform encoding on training and testing dataset to differentiate between different labels and assign them to 0 or 1

In [34]:

Encoder = LabelEncoder()
y_train_svm = Encoder.fit_transform(y_train)
y_test_svm = Encoder.fit_transform(y_test)
SVM = svm.SVC(C=1.0, kernel = 'linear', degree = 3, gamma = 'auto')
SVM.fit(X_train,y_train_svm)
predictions_SVM = SVM.predict(X_test)
print("Accuracy: ", accuracy_score(predictions_SVM, y_test_svm)*100)